# This is a basic workflow that is manually triggered

name: Manual workflow

env:
  # Username/email used to commit to Cloud Manager's Git repository
  USER_NAME: mani90
  USER_EMAIL: mani12316@gmail.com
  GH_TOKEN: ${{ github.token }}
  # Directory within the Cloud Manager Git repository
  PROJECT_DIR: project-a
  # Cloud Manager's Git repository
  MAIN_REPOSITORY: https://$MAIN_USER:$GH_TOKEN@github.com/mani90/aem-monorepo.git
  # The branch in Cloud Manager's Git repository to push to
  MAIN_BRANCH : main
  PAT: ${{secrets.GH_PAT}}

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   push:
     branches: [ main ]
permissions:
   contents: write  # To push a branch
   pull-requests: write 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout this project into a sub folder
      - uses: actions/checkout@v2
        with:
          path: sub
      - uses: actions/checkout@v2
        with: 
          repository: mani90/aem-monorepo
          path: main
          token: ${{secrets.GH_PAT}}
          ref: main
      # Cleanup sub project
      - name: Clean project
        run: |
          git -C sub log --format="%an : %s" -n 1 > commit.txt
          rm -rf sub/.git
          rm -rf sub/.github
      # Set global git configuration
      - name: Set git config
        run: |
          git config --global credential.helper cache
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
      # Move sub project
      - name: Move project to main project
        run: |
          rm -rf ${MAIN_BRANCH}/${PROJECT_DIR}
          mv sub ${MAIN_BRANCH}/${PROJECT_DIR}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GH_PAT}}
          branch: main
          repository: mani90/aem-monorepo
          force: true
          directory: main
      - name: Commit Changes
        run: |
          git -C ${MAIN_BRANCH} add -f ${PROJECT_DIR}
          git -C ${MAIN_BRANCH} commit -F ../commit.txt
          git -C ${MAIN_BRANCH} push
        env:
          token: ${{github.token}}
